// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRugwFO-Z0GQ-o4qV3H_l_Fac_PXvpc1Q',
    appId: '1:103847852380:web:ee047d29c5b08b165b2999',
    messagingSenderId: '103847852380',
    projectId: 'englifun-app',
    authDomain: 'englifun-app.firebaseapp.com',
    databaseURL:
        'https://englifun-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'englifun-app.appspot.com',
    measurementId: 'G-5V9S13QDL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbIA04onpvVvNji0zeVAh5GwLPr1IHc3k',
    appId: '1:103847852380:android:2bb9abe33ae09f345b2999',
    messagingSenderId: '103847852380',
    projectId: 'englifun-app',
    databaseURL:
        'https://englifun-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'englifun-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5qMuM_7VmTfYmVXnGHSz-LPFg8Du49PQ',
    appId: '1:103847852380:ios:1dadb73f3d79e4805b2999',
    messagingSenderId: '103847852380',
    projectId: 'englifun-app',
    databaseURL:
        'https://englifun-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'englifun-app.appspot.com',
    iosClientId:
        '103847852380-5bqs0mbgf5ecjpgrg0luaklm210f0gnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shiningworld',
  );
}
